baseURL: "https://ashlab.net" 
title: Alex Huang
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: 'ij.pdf'
          weight: 6

params:
    description: "personal website of ash"
    author: ashlab
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "November 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Alex Huang
          subtitle: "I am currently a research intern at <a href='https://www.chicagobooth.edu/' style='text-decoration: none; border-bottom: 1px solid currentColor;'>University of Chicago Booth School of Business</a> working with <a href='https://pranavnuti.su.domains/' style='text-decoration: none; border-bottom: 1px solid currentColor;'>Pranav Nuti</a> and <a href='https://faculty.chicagobooth.edu/rad-niazadeh' style='text-decoration: none; border-bottom: 1px solid currentColor;'>Rad Niazadeh</a> on online matching secretary problems. <br><br>
          
          I recently obtained my master's degree in Computational and Applied Mathematics from the <a href='https://www.uchicago.edu/' style='text-decoration: none; border-bottom: 1px solid currentColor;'>University of Chicago</a>, advised by <a href='https://congma1028.github.io/' style='text-decoration: none; border-bottom: 1px solid currentColor;'>Cong Ma</a>. I previously studied Operations Research: Financial Engineering at <a href='https//www.columbia.edu' style='text-decoration: none; border-bottom: 1px solid currentColor;'>Columbia University</a>, with a minor in Applied Mathematics. <br><br>
          
          You can find my CV <a href='cv-11-25.pdf' style='text-decoration: none; border-bottom: 1px solid currentColor;'>here</a>."
          imageUrl: "prof4.jpg"
          imageWidth: 200
          imageHeight: 300
        
          buttons:
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: archive/

    socialIcons:
        - name: Email
          url: alexhuang@uchicago.edu
        - name: GitHub
          url: https://github.com/lovesqualor

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "ash"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2