baseURL: "https://alhu.net" 
title: alhu
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies: {}

menu:

params:
    description: "personal website of ash"
    author: ashlab
    googleAnalyticsID: "G-174EBPET11"
    DateFormat: "November 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Alex Huang
          subtitle: "I am currently a research intern at the <a href='https://www.chicagobooth.edu/' style='text-decoration: none; border-bottom: 1px solid currentColor;'>University of Chicago Booth School of Business</a> working with <a href='https://pranavnuti.su.domains/' style='text-decoration: none; border-bottom: 1px solid currentColor;'>Pranav Nuti</a> and <a href='https://faculty.chicagobooth.edu/rad-niazadeh' style='text-decoration: none; border-bottom: 1px solid currentColor;'>Rad Niazadeh</a> on online matching problems. I've written a note with some new results, which you can find <a href='noteonmatchings.pdf' style='text-decoration: none; border-bottom: 1px solid currentColor;'>here</a> (draft).<br><br>
          
          I recently obtained my master's degree in Computational and Applied Mathematics from the <a href='https://www.uchicago.edu/' style='text-decoration: none; border-bottom: 1px solid currentColor;'>University of Chicago</a>, advised by <a href='https://congma1028.github.io/' style='text-decoration: none; border-bottom: 1px solid currentColor;'>Cong Ma</a>. I previously studied Operations Research: Financial Engineering at <a href='https//www.columbia.edu' style='text-decoration: none; border-bottom: 1px solid currentColor;'>Columbia University</a>, with a minor in Applied Mathematics. <br><br>
          
          You can find my CV <a href='Alex-Huang-CV-1764457225.pdf' style='text-decoration: none; border-bottom: 1px solid currentColor;'>here</a>. 
          <br><br>

          <b>Misc:</b> 
          My GitHub username references <a href='https://en.wikipedia.org/wiki/For_Esmé—with_Love_and_Squalor' style='text-decoration: none; border-bottom: 1px solid currentColor;'>this devastating Salinger story</a>, which I wouldn't recommend you read, if you wish to be happy."

          imageUrl: "prof4.jpg"
          imageWidth: 200
          imageHeight: 300

    socialIcons:
        - name: GitHub
          url: https://github.com/lovesqualor

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "ash"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2